services:
  nginx:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: mkpong/gateway-nginx:latest

  react:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: mkpong/odn-frontend-react:latest
  
  flask-user:
    build:
      context: ./backend/userService
      dockerfile: dockerfile
    image: mkpong/user-service-flask:latest

  flask-dataset:
    build:
      context: ./backend/datasetService
      dockerfile: dockerfile
    image: mkpong/dataset-service-flask:latest

  flask-comment:
    build:
      context: ./backend/commentService
      dockerfile: dockerfile
    image: mkpong/comment-service-flask:latest

  flask-transfer:
    build:
      context: ./backend/transferService
      dockerfile: dockerfile
    image: mkpong/transfer-service-flask:latest
  
  minio:
    build:
      context: ./backend/transferService/minio
      dockerfile: dockerfile
    image: mkpong/transfer-db-minio:latest
  
  mysql-user:
    build:
      context: ./backend/userService/mysql
      dockerfile: dockerfile
    image: mkpong/user-db-mysql:latest

  mysql-dataset:
    build:
      context: ./backend/datasetService/mysql
      dockerfile: dockerfile
    image: mkpong/dataset-db-mysql:latest
  
  mysql-comment:
    build:
      context: ./backend/commentService/mysql
      dockerfile: dockerfile
    image: mkpong/comment-db-mysql:latest