services:
  userdb:
    image: user-db-mysql
    build:
      context: ./backend/userService/mysql
    ports:
      - "3307:3306"

  transferminio:
    image: transfer-db-minio
    build:
      context: ./backend/transferService/minio
    ports:
      - "9005:9005"
      - "9006:9006"

  datasetdb:
    image: dataset-db-mysql
    build:
      context: ./backend/datasetService/mysql
    ports:
      - "3309:3306"
  
  commentdb:
    image: comment-db-mysql
    build: 
      context: ./backend/commentService/mysql
    ports:
      - "3310:3306"

  userservice:
    image: user-service-flask
    build:
      context: ./backend/userService
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - userdb
    command: ["./wait-for-it.sh", "userdb:3306", "--", "flask", "run", "--host", "0.0.0.0"]

  transferservice:
    image: transfer-service-flask
    build: 
      context: ./backend/transferService
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - transferminio
    command: ["./wait-for-it.sh", "transferminio:9005", "--", "flask", "run", "--host", "0.0.0.0"]

  datasetservice:
    image: dataset-service-flask
    build:
      context: ./backend/datasetService
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - datasetdb
    command: ["./wait-for-it.sh", "datasetdb:3306", "--", "flask", "run", "--host", "0.0.0.0"]

  commentservice:
    image: comment-service-flask
    build:
      context: ./backend/commentService
    ports:
      - "5004:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - commentdb
    command: ["./wait-for-it.sh", "commentdb:3310", "--", "flask", "run", "--host", "0.0.0.0"]

  frontend:
    image: odn-frontend-react
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
