services:
  userservice:
    image: user-service-flask
    build:
      context: ./backend/userService
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development


  transferservice:
    image: transfer-service-flask
    build: 
      context: ./backend/transferService
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development


  datasetservice:
    image: dataset-service-flask
    build:
      context: ./backend/datasetService
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development

  commentservice:
    image: comment-service-flask
    build:
      context: ./backend/commentService
    ports:
      - "5004:5000"
    environment:
      FLASK_ENV: development

  frontend:
    image: odn-frontend-react
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

