apiVersion: v1
kind: Service
metadata:
  name: minio-transfer-service
spec:
  selector:
    app: minio-transfer
  ports:
    - name: minio
      protocol: TCP
      port: 9005
      targetPort: 9005
    - name: console
      protocol: TCP
      port: 9006
      targetPort: 9006
      nodePort: 30006
  type: NodePort