apiVersion: v1
kind: Service
metadata:
  name: mysql-user-service
spec:
  selector:
    app: mysql-user
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-dataset-service
spec:
  selector:
    app: mysql-dataset
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-comment-service
spec:
  selector:
    app: mysql-comment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
