apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-user-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/jimmy/ex_storage/database/mysql-user  # 호스트 디렉토리 경로
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dataset-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/jimmy/ex_storage/database/mysql-dataset  # 호스트 디렉토리 경로
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-comment-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/jimmy/ex_storage/database/mysql-comment  # 호스트 디렉토리 경로
  persistentVolumeReclaimPolicy: Retain