apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000  # 임의의 노드 포트
  selector:
    app: react-app