name: Deploy MSA server

on:
  push:
    branches: ["main"]

permissions: write-all

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dev Server Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 220.149.232.224
          username: jimmy
          password: dlwodud3424!
          script: |
            cd ex_storage/OpenDataNexus-ODN
            cd dockerDB
            docker-compose up -d
            cd ..
            docker-compose up -d
